####################################################################
# Census Getter Properties
####################################################################
state: 53
counties: ['035', '033', '053', '061']
county_map:
  King County: 53033
  Kitsap County: 53035
  Pierce County: 53053
  Snohomish County: 53061
base_year: 2023
forecast_year: 2050

# Must create Env Variable holding census key. Put name of Var here:
census_key: CENSUS_KEY

pums_type: 1-Year # 1-Year of 5-Year

# Local Data
# ------------------------------------------------------------------
data_dir: data
output_dir: data # put output tables in data dir for easy access by popsim

# since REMI forecasts probably shouldn't be stored in the repo they will automatically
# be copied to the data directory from the network path below if missing 
regional_forecasts_dir: J:\Projects\Forecasts\_Regional\2026\REMI

regional_forecast:
  - tablename: regional_controls
    # filename: REMI_base_adj_to_OFM.xlsx
    # filename: REMI_v3.3.xlsx
    # filename : REMI_OFM_v2022_Low.xlsx
    filename : REMI_OFM_v2022_Medium.xlsx
    # filename : REMI_OFM_v2022_High.xlsx
    # filename : REMI_controls_test_high.xlsx
    # filename : REMI_controls_test_low.xlsx
    # filename : PUMS_test.xlsx

input_table_list:
  - tablename: occupation_crosswalk
    filename: occupation_crosswalk.csv
  - tablename: industry_crosswalk
    filename: industry_crosswalk.csv

pums_table_list:
  - tablename: pums_hh
    filename: psam_h53.csv
  - tablename: pums_person
    filename: psam_p53.csv
  - tablename: puma_geog_lookup
    filename: puma_geog_lookup_cnty.csv

output_table_list:
  # - tablename: seed_households
  #   filename: seed_households.csv
  # - tablename: seed_persons
  #   filename: seed_persons.csv
  - tablename: county_controls
    filename: remi_controls.csv
  - tablename: region_summed
    filename: region_summed.csv
  - tablename: counties_summed
    filename: counties_summed.csv
  - tablename: counties_summed_all_years
    filename: counties_summed_all_years.csv
  - tablename: gq_rates
    filename: gq_rates_acs1yr_2023.csv
  - tablename: headship_rates
    filename: headship_rates_acs1yr_2023.csv

nan_fill: 0
urbansim_baseyear_cache: L:/base_year_2023_inputs/urbansim2_cache/2023
comparison_controls_store: data/comparison_cache.h5
comparison_controls_table: /annual_household_control_totals

# pypyr steps to run
steps:
#  - regional_controls.steps.puma_county_lookup
#  - regional_controls.steps.pums_download
#  - regional_controls.steps.prepare_pums
#  - regional_controls.steps.comparison_cache_to_hdf5
#  - regional_controls.steps.load_data
#  - regional_controls.steps.remi_controls
 - regional_controls.steps.write_tables
#  - regional_controls.steps.run_popsim
#  - regional_controls.steps.archive_popsim_output
#  - regional_controls.steps.results_summaries
#  - regional_controls.steps.render_dashboard